export default {
  SHOWS_OPEN_TO_PUBLIC: 'SHOWS_OPEN_TO_PUBLIC',
  PA_SYSTEM: 'PA_SYSTEM',
  PARKING_AVAILABLE: 'PARKING_AVAILABLE',
  BILL_AVAILABLE: 'BILL_AVAILABLE',
  ACCESSIBLE: 'ACCESSIBLE',
  PETS_LIVESTOCK: 'PETS_LIVESTOCK',
  HAS_PREP_ROOM: 'HAS_PREP_ROOM',
  MUSIC_ON_PATIO_OR_OUTSIDE: 'MUSIC_ON_PATIO_OR_OUTSIDE',
  MUSIC_INSIDE: 'MUSIC_INSIDE',
  FOOD_AVAILABLE: 'FOOD_AVAILABLE',
};
