const AmenityTypes = Object.freeze({
  PA_SYSTEM_AVAILABLE: 'PA_SYSTEM_AVAILABLE',
  IN_HOUSE_BACKLINE: 'IN_HOUSE_BACKLINE',
  ALL_AGES_SHOWS: 'ALL_AGES_SHOWS',
  DRINKING_AGE_ONLY: 'DRINKING_AGE_ONLY',
  HAS_PREP_ROOM: 'HAS_PREP_ROOM',
  BILL_AVAILABLE: 'BILL_AVAILABLE',
  MUSIC_ON_PATIO_OR_OUTSIDE: 'MUSIC_ON_PATIO_OR_OUTSIDE',
  MUSIC_INSIDE: 'MUSIC_INSIDE',
  FOOD_AVAILABLE: 'FOOD_AVAILABLE',
  ACCESSIBLE: 'ACCESSIBLE',
  PARKING_AVAILABLE: 'PARKING_AVAILABLE',
  PETS_LIVESTOCK: 'PETS_LIVESTOCK',
  SHOWS_OPEN_TO_PUBLIC: 'SHOWS_OPEN_TO_PUBLIC',
  DJ_TURNTABLES: 'DJ_TURNTABLES',
});

export default AmenityTypes;
