export const SELECTED_EVENT_REQUESTED = 'SELECTED_EVENT_REQUESTED';
export const SELECTED_EVENT_RECEIVED = 'SELECTED_EVENT_REQUESTED';
export const SELECTED_EVENT_FAILED = 'SELECTED_EVENT_FAILED';

export const UPDATE_PUBLISH_STATE = 'UPDATE_PUBLISH_STATE';

export const CREATE_TICKET_GROUP_REQUESTED = 'CREATE_TICKET_GROUP_REQUESTED';
export const CREATE_TICKET_GROUP_RECEIVED = 'CREATE_TICKET_GROUP_RECEIVED';
export const CREATE_TICKET_GROUP_FAILED = 'CREATE_TICKET_GROUP_FAILED';

export const SET_SELECTED_TICKET_GROUP = 'SET_SELECTED_TICKET_GROUP';

export const UPDATE_TICKET_GROUP_HOLDER = 'UPDATE_TICKET_GROUP_HOLDER';
export const ADD_TICKET_GROUP_HOLDER = 'ADD_TICKET_GROUP_HOLDER';
export const DELETE_TICKET_GROUP_HOLDER = 'DELETE_TICKET_GROUP_HOLDER';

export const FOLLOW_EVENT = 'FOLLOW_EVENT';
export const UNFOLLOW_EVENT = 'UNFOLLOW_EVENT';

export const FOLLOW_ORGANIZER = 'FOLLOW_ORGANIZER';
export const UNFOLLOW_ORGANIZER = 'UNFOLLOW_ORGANIZER';

export const ADD_VENUE_ITEM = 'ADD_VENUE_ITEM';
export const REMOVE_VENUE_ITEM = 'REMOVE_VENUE_ITEM';
export const VENUE_ITEM_UPDATED = 'VENUE_ITEM_UPDATED';
export const VENUE_MAP_UPDATED = 'VENUE_MAP_UPDATED';
export const SELECT_MAP_NODE = 'SELECT_MAP_NODE';
export const UPDATE_NODE_FIELD = 'UPDATE_NODE_FIELD';

export const VENUE_MAP_UPDATED_REQUESTED = 'VENUE_MAP_UPDATED_REQUESTED';
export const VENUE_MAP_UPDATED_RECEIVED = 'VENUE_MAP_UPDATED_RECEIVED';
export const VENUE_MAP_UPDATED_FAILED = 'VENUE_MAP_UPDATED_FAILED';

export const VENUE_MAP_FETCHED = 'VENUE_MAP_FETCHED';
export const VENUE_MAP_CREATED = 'VENUE_MAP_CREATED';
export const FETCH_VENUES_LIST = 'FETCH_VENUES_LIST';

export const UPDATE_TICKET_TIERS = 'UPDATE_TICKET_TIERS';
export const UPDATE_SEAT_MAPPING = 'UPDATE_SEAT_MAPPING';
export const DELETE_TICKET_TIER = 'DELETE_TICKET_TIER';

export const FETCHED_TICKET_REVENUE_BY_TICKET_GROUP =
  'FETCHED_TICKET_REVENUE_BY_TICKET_GROUP';
export const FETCHED_TICKET_REVENUE = 'FETCHED_TICKET_REVENUE';

export const FETCH_MARKETPLACE_TICKETS =
  'app/EventPage/FETCH_MARKETPLACE_TICKETS';
export const ARTIST_PROFILE_CREATE = 'ARTIST_PROFILE_CREATE';
